### ISSUE TITLE
Item de Configuração

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#100]
**Tarefa: configItem/GCS**

1. Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". 

Podemos ter um único arquivo como item de configuração?

Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?

Para ambas as perguntas a resposta é sim. Consideremos que um item de configuração pode ter diversos produtos de trabalho, como também pode ter apenas um. Portanto, ainda que entidades individuais, itens de configuração podem ser conjuntos de produtos de trabalho formados por diversos arquivos.

2. Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?

O que o Wikipedia expressa ao indicar a necessidade dos itens de configuração serem identificados unicamente, assim como a MPS.BR, é a necessidade de controlá-los. Conforme o resultado esperado GCO 4. é necessário atualizar o status dos itens de configuração de maneira que se possua tanto histórico de alterações como um status atual. OS GCO 5 e 6 demonstram também a necessidade de controlar suas modificações, armazenamento, manuseio e liberações. Este controle não seria possível sem que cada item tivesse um identificador próprio que facilitasse seu gerenciamento e busca, correndo risco de confundirmos e realizarmos updates em um item incorreto. Afinal, ele estão sob baseline e quase sempre não será apenas um.

3. Uma issue no Github pode ser considerada um item de configuração?

Tudo depende da forma com a qual será usada. Nós temos o costume de aproveitar funcionalidades para cumprir funções para as quais não foram originalmente criadas. Uma Issue quando utilizada para gerenciar um componente que necessita de configuração para que o serviço seja entregue, sendo ela registrada por código de identificação único, sim. Afinal, uma issue pode ser aberta, fechada, aceita, assinada, etc. Todos os parâmetros de controle, considerando que o serviço está descrito na baseline que é o repositório, inclusive a aceitação da solução e alteração na baseline garantem que ela atenda aos requisitos.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Pedro, não se esqueça de reabrir os tópicos 01, 02 e 03 pois ficaram SEM APROVEITAMENTO (por conta da entrega fora do prazo). Conforme o tópico 07, é a oportunidade de reabrir e refazer dentro do novo prazo.
