### ISSUE TITLE
conceitos

### ISSUE THREAD

**Issue by cleydsonjr** [kyriosdata/git#109]
**Tarefa: Tópico 06**

realizado

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
CLEYDSON, não se esqueça de fazer os tópicos 03, 04 e 05. Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
