### ISSUE TITLE
Conceitos

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#111]
**Tarefa: T06**
Realizado.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Marcos, não se esqueça de reabrir o tópico 01 e 02. Está fechado sem aproveitamento devido entrega fora do prazo. Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
