### ISSUE TITLE
Conceitos

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#112]
**Tarefa: commandsGit/GCS**

Realizado

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Pedro, não se esqueça de reabrir os tópicos 01, 02 e 03. Está fechado sem aproveitamento devido entrega fora do prazo. Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
