### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by pauloj2000** [kyriosdata/git#113]
**Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.**

Os itens de configuração são identificados com base em critérios estabelecidos;
Os itens de configuração sujeitos a um controle formal são colocados sob baseline;
A situação dos itens de configuração e das baselines é registrada ao longo do tempo e disponibilizada; Modificações em itens de configuração são controladas;
O armazenamento, o manuseio e a liberação de itens de configuração e baselines são controlados;
Auditorias de configuração são realizadas objetivamente para assegurar que as baselines e os itens de configuração estejam íntegros, completos e consistentes;
As informações de itens de configuração são comunicadas às partes interessadas;

**Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.**

Gerência de Configuração é estratégia e os métodos para coordenar o desenvolvimento de software mantendo registrado e seguro o desenvolvimento do software e evitando confusões.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
