### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by pauloj2000** [kyriosdata/git#114]
**1** - Com certeza, poderiamos ter um único arquivo ou um item que agrupa vários arquivos, mas ele deve ser tratado como uma entidade singular pelo processo de gerência de configuração.

**2** - Sim, a entidade deve ser identificada como única para que ela possa ser distinguida de todos os outros itens de configuração.
O processo de GCO também espera que tal identificação seja realizada, tendo como resultado uma identificação feita por critérios preestabelecidos.

**3** - Correto, pois a issue também possui um identificador único e é gerada como um produto de trabalho durante o processo de gerência de configuração.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
