### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by trete** [kyriosdata/git#116]
•"Gerência de Configuração (GCO), ou ainda Software Configuration Management (SCM), tem como propósito **estabelecer** e **manter** a **integridade** de todos os **produtos de trabalho** de um **projeto** e **disponibilizá-los** a todos os **envolvidos**". Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.
 Estabelecer trata-se de identificar os itens de configuração do projeto e criar um ambiente que possa arquivar suas versões ao longo do desenvolvimento.
 
Manter trata-se de persistir a estrutura que armazena as baselines.
 
Integridade trata-se de garantir que os itens de configuração não tenham seus históricos de atualização comprometidos para 
que as alterações possam ser revertidas.
 
Produtos de trabalho tratam-se de artefatos usados, produzidos, ou alterados pela execução de um processo.
 
Projeto é um empreendimento temporário para criar um produto ou serviço único com elaboração progressiva.
 
Disponibilização diz respeito a garantir o acesso ao produto ou serviço desenvolvido assim que estiver pronto.
 
Envolvidos são os stakeholders, usuários e as pessoas que trabalham no projeto.

•Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.
O propósito da gerência de configuração é criar um ambiente que permita a visualização dos artefatos produzidos pelo projeto para que possam ser continuamente mantidos, avaliados e até revertidos a versões anteriores caso necessário.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
