### ISSUE TITLE
Aproveitamento nos tópicos

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#117]
**Tarefa: T07**
Aproveitamento nos tópicos.

Reabertura e re-checagem das seguintes tarefas:
https://github.com/kyriosdata/git/issues/62 (T01)
https://github.com/kyriosdata/git/issues/63 (T02)
https://github.com/kyriosdata/git/issues/65 (T03)

**Comment by willianjferreira** [comment]
Atividades reabertas.
Alteradas para : COM APROVEITAMENTO :+1:
