### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#118]
**1. Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.**

> Os itens de configuração são identificados com base em critérios estabelecidos;
> Os itens de configuração sujeitos a um controle formal são colocados sob baseline;
> A situação dos itens de configuração e das baselines é registrada ao longo do tempo e disponibilizada; Modificações em itens de configuração são controladas;
> O armazenamento, o manuseio e a liberação de itens de configuração e baselines são controlados;
> Auditorias de configuração são realizadas objetivamente para assegurar que as baselines e os itens de configuração estejam íntegros, completos e consistentes;
> As informações de itens de configuração são comunicadas às partes interessadas;

**2. Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.**

> É um processo que disponibiliza de técnicas e métodos para tornar acessível todos os produtos de software relevantes (seja código, documentação ou outros) aos interessados seja no presente ou futuro

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
