### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#119]
**Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**

> Sim, um item de configuração pode envolver diversos arquivos ou produtos, desde que seja entendido como uma entidade única e o processo de configuração seja consistente com esses produtos. Podemos considerar o exemplo como item de configuração "código fonte" por exemplo que pode conter um ou mais arquivos de código

**Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**

> O GCO espera um identificador único da mesma forma que cada item tem que ter um processo estabelecido, a forma de controlar e registrar a evolução dos produtos de software necessita que eles estejam identificados unicamente

**Uma issue no Github pode ser considerada um item de configuração?**
> Sim, da mesma forma que arquivos de código, o conjunto de issues pode ser considerado uma entidade única e um item de configuração com processos definidos.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
