### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#120]
1.
- Estabelecer: identificar, selecionar os itens passiveis de gerencia de configuração. mapear esses itens dando identificadores únicos, descrever esses itens.

- Manter a integridade: toda mudança precisa passar por um crivo para que seja possível manter as coisas em ordem. caso seja aprovada, então essa mudança é classificada, priorizada em relação a outras demandas de mudança. Após, é realizada uma análise do impacto e posteriormente a abertura de um projeto de manutenção (prazo, escopo, custo, proposta de como será feita mudança).

- Produtos de trabalho: são os artefatos produzidos durante a execução do processo.

- Projeto: como preconiza o PMI, é um esforço temporário para alcançar um produto, serviço ou resultado único, por meio de processos, métodos, e ferramentas. 

- Disponibilizar:  Trata-se da identificação das versões de cada item a ser disponibilizado e da entrega do produto ao ambiente de produção.

- Envolvidos: Os stakeholders. Todos que são afetados direta ou indiretamente pelos resultados da gerência de configuração. Isso inclui desenvolvedores, gestores, fornecedores e clientes.

2. A gerência de configuração tem como propósito identificar, controlar, avaliar e entregar itens de configuração para garantir a integridade de uma configuração estável que garanta o sucesso do serviço, produto ou resultado único que os stakeholders almejam.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
