### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#121]
1. Sim. Todos os itens produzidos durante o projeto são itens de configuração e eles possuem diferentes níveis de granularidade. Sendo assim, temos itens que continuem itens maiores e temos itens que são constituídos por diversos itens. Um bom exemplo seria uma metodologia, ela é constituída de processo, ferramentas e métodos e todos os citados são produtos de trabalho.

2. Todo item de configuração de possuir um identificador único, no resultado esperado n2 esse detalhe é citado. GCO2 - Os itens de configuração são identificados com base em critérios estabelecidos.

3. Considerando que um item de configuração e um produto de trabalho são o mesmo e tudo que é criado durante a execução de um processo/projeto é considerado produto de trabalho, Sim.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
