### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#126]
Tarefa: adSearch/GCS

Como realizar a seguinte busca no Github: Listar todas as issues com um determinado título (opcional), criada por determinado usuário, em um dado repositório.
Opção 1: Direto no repositório

Ao selecionar a guia Issues de um determinado repositório que se queira consultar, aparecerá a opção de filtros para listar problemas e pull requests. Nestes filtros você fará a uma análise mais alto nível, podendo selecionar Issues criadas, assinadas ou mencionadas pelo usuário que está acessando. Ao filtrar, no título das colunas da lista gerada você pode adicionar filtros adicionais como Autores, Labels, Projetos, Assinaturas, além de conseguir ordenar por data de criação, atualização ou comentário na Issue.

Opção 2: Por meio da API de consulta do Github (diferente da opção 1, você também pode buscar repositórios específicos à partir dos filtros)

Esta API deve ser acessada via URL https://github.com/search/advanced.

A primeira table refere-se as opções avançadas de busca. Nela você consegue filtrar:

Proprietários;
Repositórios;
Período de criação;
Linguagem utilizada.
A segunda table refere-se as opções de filtro dos repositórios. Nela você consegue filtrar:

Por quantidade de rates;
Quantidade de forks;
Tamanho em kb;
Data do Push;
Licença inserida.
A terceira table refere-se as opções de filtro dos códigos. Nela você consegue filtrar:

Extensão dos arquivos;
Tamanho da pasta;
O path ou caminho do arquivo;
O nome de alguma pasta.
A quarta table refere-se as opções de filtro nas Issues. Nela você consegue filtrar:

O estado da Issue. Se está aberta ou fechada;
A quantidade de comentários;
Pelo nome das labels;
Pelo autor que abriu a Issue;
Pelos usuários mencionados;
Pelos usuários que assinaram algum push;
Pela data limite de atualização da Issue.
A quita table refere-se as opções de filtro nos usuários. Nela você consegue filtrar:

Nome completo;
Localização;
Quantidade de seguidores;
Quantidade de repositórios públicos;
Linguagem utilizada;
Um exemplo de busca: user:pedropirescg stars:4 forks:3 fullname:"Pedro Henrique Pires" language:JavaScript

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
