### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#15]
Meu nome: Augusto Borges de Moura
Meu registro acadêmico: 201602485
Minha conta no github: http://github.com/augustobmoura/gcs-2020-01

**Comment by willianjferreira** [comment]
Augusto, por favor confirme se o repositório está publico.

**Comment by augustobmoura** [comment]
Estava privado mesmo, mudei a visibilidade

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
