### ISSUE TITLE
Explicação de Ausência

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#171]
**Esta explicação não é uma justificativa**

Boa tarde, Professor!

Estou neste momento atualizando todas as atividades. Nas últimas semanas estive em viagem a trabalho e hoje estou de folga para poder atualizar tudo. Estava em viagem para o interior e fica bastante complicado utilizar a internet.

Não há problema se não puder considerar as atividades. Estou enviando explicação para o caso de servir como peso em sua tomada de decisão. Tentarei finalizar todas até meia noite, porque todas as matérias atrasaram. 

No link a seguir está documento assinado digitalmente pela empresa comprovando autenticidade das minhas informações. Há também dados de contato no Timbrado caso valha o contato. Gratidão!

https://na2.documents.adobe.com/public/fs?aid=CBFCIBAA3AAABLblqZhAAtbYprIsZeeuheniakXw-9nHo_onZHPkfyIwl9kFhoJ0Qh5G5NbZfwL4TDPDMu1I%2A

**Comment by kyriosdata** [comment]
Pedro, a disciplina foi planejada para se adequar a um cenário bem mais flexível do que aquele que seria o presencial. As atividades estão ajustadas para o "remoto", e com prazo razoável "largo" para a entrega, dentre outras mudanças. 

Em tempo, não é preciso o link para o documento acima, sugiro que o remova, até porque está disponibilizado publicamente. 
Vamos em frente!
