### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#174]
**Tarefa: 13**

Escolhi o projeto "vibração" (https://github.com/flutter/flutter.git) que possui 104553 estrelas.
Segundo o que percebi, são muito abertos a receber  ideias e correções, porém seguem algumas normas para isso. Por exemplo, antes de abrir um Pull Request(PR), você deve abrir uma Issue com a questão que deseja corrigir/acrescentar para que seja discutido entre os mantenedores. Dessa forma garantem a melhor solução ou chegam a conclusão de que a forma atual realmente é a melhor e não deve ser alterada. Caso sua Issue seja aprovada, depois de discutida, você pode abrir um PR se atentando para que seja um PR por correção. Segundo o que indicam seu  PR pode demorar algumas semanas para ser aceito, já que passará por avaliações onde poderão pedir que seja feito alterações antes que seja aprovado e aceito no projeto. De início você não tem acesso de contribuidor o que te impede, por exemplo, de mesclar seus PR's mesmo após aprovação. Mas a partir da hora que vários PR's são aceitos com sucesso, sem orientação extensiva e seus códigos forem considerados de qualidade, você passará a receber acesso de contribuidor, o que te dá mais liberdade para fazer correções, triagens e contribuições para o projeto. Quando relacionado a Issues ou PR , existem triagens que devem ser observadas. São vistas questões como, prioridade, quantidade de rótulos, se existem duplicatas(issues abertas sobre a mesma questão) e  se o PR contém teste para a funcionalidade que apresenta, por exemplo. Foi observado também, que existe várias branches referentes às versões e alterações realizadas antes de serem inseridas na master. As Issues e PR são fechadas e incluídas no projeto principal por colaboradores que, após aprovados pela equipe Flutter, recebem acesso especial. Existem vários documentos que determinam as boas práticas para um colaborador Flutter que gerem desde o comportamento indivíduo-equipe até as questões técnicas aceitáveis.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
