### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by jhordangab** [kyriosdata/git#176]
O projeto escolhido foi o Bootstrap (https://github.com/twbs/bootstrap) com mais de 140K.
O Bootstrap é um framework _front-end_ que veio para facilitar e agilizar o trabalho, oferecendo padrões para HTML, JavaScript e CSS, desenvolvido por Jacob Thorton e Mark Otto.
Com mais de 20 mil _commits_, o projeto é atualizado frequentemente e o que me chamou atenção foi que a maioria foi realizada por um usuário específico (KhmikosR).
Observando os números, as issues são fechadas com bastante frequência também, já que são cerca de 330 abertas e quase 20 mil fechadas e o pessoal interage bastante através dos comentários das issues.
As _pull requests_ também são aceitas de forma inteligente, já que de cerca de 100 abertas temos mais de 11 mil fechadas e com uma grande interação pelos comentários.
Outra coisa também que não era do meu conhecimento é que a maioria dos _commits_ são "verificados" através de chaves do github.
As _branches_ são separadas em forma de atividades e também de versões do projeto.
Resumindo, o projeto do bootstrap é muito bem arquitetado, possui uma documentação bastante completa e fácil, vários validadores de teste com sucesso e não é atoa que o bootstrap é um dos _frameworks front-end opean sorce_ mais utilizados no mundo.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
