### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#177]
Repositório escolhido: facebook/react (158k stars)

Observações:

Os itens de configuração são os itens controlados pelo git. Eles seguem uma convenção de como precisam ser organizados em termos de pastas. (https://reactjs.org/docs/codebase-overview.html).  Além disso, quando algum item muda ele é divulgado num changelog, que é um arquivo que cita os itens que foram substituidos e por quais itens.

Os colaboradores interagem através da plataforma github, seguindo um código de conduta e respeitando regras definidas em documentação desenvolvida para os colaboradores, além de vários fóruns de discussão - onde as pessoas testam a aceitação de suas ideias sobre novas funcionalidades ou mudanças, webchat(IRC) e comunidade no discord.

Qualquer pessoa pode abrir uma issue com a sua intenção de desenvolver uma funcionalidade. Se a issue for aceita, o desenvolvimento da funcionalidade é liberado. Todas as mudanças desenvolvidas são registradas num changelog (https://github.com/facebook/react/blob/master/CHANGELOG.md). Outra coisa importante é que eles seguem a convenção de versionamento (semantic version - https://semver.org/lang/pt-BR/).

Todas as decisões são, de fato, tomadas pelo time do facebook. Eles que aceitam as issues e as pull requests. Ditam o rumo do framework.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
