### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#178]
Eu escolhi o bootstrap 
Link: https://gitstar-ranking.com/twbs/bootstrap
As praticas encontradas são:
1- bons padrões de commit com modelo definido e estruturado 
2- read-me bem estruturado com instruções do projeto e de colaboração
3- branchs com padrão de nomenclatura tal qual seus commits. 
4-Sistema de tags de identificação de artefatos;pratica de uso de pull request para controlle de merge.
5-sistema de versionamento padronizado

Concluindo o repositório é muito bem estruturado o que torna mais produtivo e organizado

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
