### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by kayo08** [kyriosdata/git#179]
O projeto que escolhi foi o [Golang](https://github.com/golang/go) com 7762 Stars.
GoLang é uma linguagem de programação open source criada pela Google, focada em produtividade e programação concorrente. Contando com mais de 1500 contribuidores 
Na pagina frontal do git do projeto se encontra um documento destinado a orientar a como se tornar um [contribuidor](https://golang.org/doc/contribute.html).
Atualmente com +6200 issue aberta e +34300 fechadas. Todas elas sendo devidamente rotuladas com **NeedsInvestigation** (quando 
 a issue não e totalmente e compreendia e necessita de mais informação), **NeedsDecision** (Quando a issue e relativamente compreendida porem não foi decidido a melhor maneira de resolve-la) ou **NeedsFix** (Quando a issue é totalmente compreendida e é dado o sinal verde para produzir o código para o fix). 
Ao sugerir alguma mudança é entrado num estágio de votação para decidir se será aprovado, a onde será discutido se foi recusado, caso precise de algumas alterações ou se foi aprovado. Caso aprovado algum dos aprovadores irá direciona-lo ao master branch.

No geral conclui que é um projeto que possui bastante interações entre os contribuidores, cada decisão e bastante discutida pela comunidade. Possuindo um boa organização nos códigos e nas documentações.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
