### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by lucianomenddes** [kyriosdata/git#180]
O projeto selecionado foi o  Shopify (https://github.com/Shopify)  com  87542 estrelas  uma plataforma para ecommerce. O projeto está estruturado em 573 repositorios, o repositorio escolhido para observações liquid  se trata de uma  linguagem open source escrita em ruby criada pela a shopify para carregar conteúdo dinâmicos nas paginas das lojas virtuais, com 152 colaborador, 141 issue open e 490 issue closed, 47 pull requests open e 642 pull requests closed.

         Cada itens de configuração está definido nas estruturas de diretorios do projeto, os colaboradores interagem principalmente pelas as issues onde cada colaborador pode abrir e fecha uma issue e também registra as mudanças e possíves bugs. 
          As mudanças no projeto são feita através de uma Pull request, qualquer um contribuitor do projeto pode avaliar o pull request e aceitar a soliciatação e fazer o merge para a branch master.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
