### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#183]
O projeto escolhido foi o [mirror do kernel Linux](https://github.com/torvalds/linux) próximo de 100 mil estrelas no momento.

O projeto linux na verdade foi a motivação inicial do Git e por isso sua história está diretamente ligada ao desenvolvimento do Github e todos os outros projetos na rede. Por muito tempo o projeto do kernel Linux utilizava uma ferramenta proprietária de versionamento chamada BitKeeper, em um momento específico Larry McVoy (criador e mantenedor do BitKeeper) decide remover o direito de uso gratuito da ferramenta alegando engenharia reversa de outra ferramenta por outro desenvolvedor. Depois de muitos desenvolvedores do kernel abrirem mão dos seus acessos do BitKeeper justamente pela barreira proprietária e monetária Linus Torvalds incia o projeto e desenvolvimento de uma nova ferramenta de versionamento, tendo como pontos principais de design que uma modificação repassada entre usuários (patches) não deveria demorar mais que 3s para ser aplicada, ser totalmente distribuída: todo usuário/desenvolvedor mantém em seu repositório git todo o histórico do projeto desde o primeiro commit, e incluir fortes proteções contra corrupções e modificações maliciosas ou acidentais, este novo projeto quando lançado se chamou Git.

O repositório oficial do git não é hospedado pelo github, é hospedado em vários servidores e serviços de companias privadas a faculdades e universidades, sendo o repositório do próprio Linus considerado não oficialmente como o principal. O repositório presente no github é apenas uma versão espelhada desses repositórios tudo graças as escolhas de arquitetura distribuída e forte integração com ferramentas externas do Git.

Os contribuidores tem que gerar um arquivo patch e enviar sua contribuição em formato de email para uma mailing list, a qual é seguida por diversos contribuidores principais de diversas organizações no mundo e o próprio Linus, de acordo com sua descrição e explicação (as mensagens de commits são bem criteriosas, é necessário explicar de forma sucinta e técnica as modificações e motivações do patch) o patch é avaliado minuciosamente e bastante estritamente por mais de um desenvolvedor até que seja aceito, descartado ou sejam solicitadas mudanças, quando aceito o patch é aplicado nos repositórios principais e os demais espelhos sincronizam as modificações entre si. Caso sua modificação seja aceita você entra para um seleto número de pessoas que teve contribuições adicionadas ao kernel Linux.

Versões pré lançamento são testadas incansavelmente em diversas suítes de testes tanto particulares quanto públicas, quando a comunidade está satisfeita com o que já foi adicionado da última versão até então novas funcionalidades são congeladas para uma nova versão e começa um trabalho minucioso de testar e estabilizar todos os testes e análises de código do kernel. Após finalizadas as correções e a versão estar estabilizada, uma nova versão do kernel é anunciada pela própria mailing list com um email do próprio Linus Torvald contendo um texto rápido e explicativo e a lista de todos os commits e contribuidores que tiveram modificações atreladas ao kernel na última versão.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
