### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by rodrigocoutinho** [kyriosdata/git#184]
**Tarefa: 13**
[https://gitstar-ranking.com/socketio/socket.io](https://gitstar-ranking.com/socketio/socket.io)
[https://github.com/socketio/socket.io](https://github.com/socketio/socket.io)

Permite comunicação em tempo real, bidirecional e baseada em eventos.

Discuções e interações través de issues e um tópico de discussions.
Não fica claro a atribuição. Porém na aba projects, somente 1 usuário permite e/ou adiciona as mudanças.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
