### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#187]
Não entendi a técnica Source Branching. Eu gostaria de entender se nessa técnica existe o objetivo dessas branches serem mescladas no futuro. Realmente não entendi a utilidade e funcionamento dessa técnica.

**Comment by kyriosdata** [comment]
Um _branch_ pode ser criado por várias finalidades, além de acrescentar uma função prevista para versão futura do software, correção de bugs e outros. Dentre elas, a experimentação, ou seja, simplesmente verificar como uma mudança, por exemplo, afeta o software. Enfim, tirando estes casos de experimentação e similares, onde não se espera que o resultado seja integrado ao código do qual a experimentação é realizada, todos os demais devem ser mesclados (_merge_) em algum momento do futuro "bem próximo". 

COM APROVEITAMENTO. 👍
