### ISSUE TITLE
T16

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#191]
Premissa fundamental:
Trabalho envolvendo grupos de pessoas numa mesma base de código pode se tornar rapidamente caótico se não houver organização da colaboração. As primeiras ideias para organizar isso são chamadas de padrões básicos.

- A primeira ideia foi ramificação do código fonte. A ideia era ramificar o código para que os colaboradores não modifiquem o mesmo código do colega, ao menos, não simultaneamente. Existem conflitos textuais e semânticos na hora de juntar esse código, sendo os semânticos os mais difíceis de resolver.

- A segunda ideia é definir uma ramificação como a principal. O estado atual do software é o que estiver na ramificação principal. Os desenvolvedores realizam seus trabalhos em ramos diferentes e quando querem compartilhar seu trabalho com os outros atualizam o ramo principal, com seu trabalho.

- A terceira ideia é executar verificações automatizadas para garantir que o código desenvolvido em algum ramo paralelo e que está tentando ser agrupado no ramo principal, possui código aceitável (saudável).

**Comment by kyriosdata** [comment]
A descrição é mínima, embora esteja dentro dos padrões. Talvez em próxima ocasião você possa discorrer um pouco mais, o que deve contribuir com a clareza. Por fim, estes padrões são BEM práticos, são concretos e a descrição sugere algo "vago", "abstrato". 

COM APROVEITAMENTO. 👍
