### ISSUE TITLE
Observações

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#192]
**Tarefa: T13**

**Observação da Gerência de Configuração em projetos famosos disponíveis no GitHub.**

Para esta análise, o projeto selecionado foi o [**React**](https://github.com/facebook/react), uma biblioteca Javascript utilizada para desenvolver interfaces de forma fácil e prática. É um dos primeiros projetos open-source gerenciados pelo Facebook.

Qualquer um pode contribuir para o projeto, desde que siga os parâmetros fornecidos no [**Guia de Contribuição**](https://reactjs.org/docs/how-to-contribute.html). Os principais deles são:

- Todas as mudanças, tanto de membros-chave do projeto quanto de usuários externos, são enviadas por meio de _pull requests_. O processo de revisão de pull requests é sempre o mesmo, **independente de quem as enviar.** 

- Todas as pull requests devem ser enviadas diretamente para o master branch. Não há branches separadas para releases futuros ou desenvolvimento.

- Antes de realizar alterações na API pública ou alterações não-triviais na implementação, deve-se **criar uma issue** para discutir tais mudanças.

- É possível entrar em contato com outros envolvidos no projeto por meio de [um canal IRC](https://webchat.freenode.net/?channels=reactjs), em [fóruns de discussão](https://reactjs.org/community/support.html#popular-discussion-forums), ou por um [servidor do Discord](https://www.reactiflux.com/).

- O projeto fornece [**exemplos de pulls requests**](https://github.com/facebook/react/issues?q=is:open+is:issue+label:%22good+first+issue%22) para que contribuintes iniciantes possam verificar as boas-práticas usadas ao se criar tais requests.

- Há um [**workflow de desenvolvimento**](https://reactjs.org/docs/how-to-contribute.html#development-workflow) recomendado para uso. Ele contém diversos casos de teste que ajudam a garantir que o código escrito não contém problemas.

- Também há um [**guia de estilos**](https://reactjs.org/docs/how-to-contribute.html#style-guide) disponível.

Em resumo, o projeto fornece uma documentação e Gerência de Configuração robusta para que até mesmo programadores iniciantes possam contribuir para o projeto de maneira confortável.

**Comment by willianjferreira** [comment]
ATIVIDADE ENTREGUE FORA DO PRAZO

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
