### ISSUE TITLE
T16

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#195]
**Tarefa: T16**

Modelos de Branching

No artigo [_Patterns for Managing Source Code Branches_](https://martinfowler.com/articles/branching-patterns.html), há três padrões de organização de branching apresentados. São eles:

**1. [Padrões com foco em integração](https://martinfowler.com/articles/branching-patterns.html#integration-patterns)**

- **Foco na integração** de códigos desenvolvidos por diferentes membros de uma equipe, utilizando-se de uma _mainline_. É necessário um gerenciamento sobre as mudanças que tais membros realizam, de forma a evitar conflitos e problemas devido às diferenças de código existentes. Esses padrões possibilitam uma redução no tempo gasto para solucionar tais divergências, diminuindo o tempo gasto pela equipe na investigação e solução de bugs gerados por commits conflitantes.

**2. [Padrões com foco na produção](https://martinfowler.com/articles/branching-patterns.html#path-to-production)**

- **Foco na disponibilidade de código estável e confiável para o branch de produção**, que é utilizado pelo usuário final. Pode-se utilizar uma _release branch_ como intermediário entre a _mainline_ e o branch de produção; a _release branch_ é basicamente uma cópia estável da _mainline_ que não aceita novas funcionalidades: o foco aqui é buscar estabilidade e corrigir quaisquer problemas antes que o código seja levado para o ambiente de produção. Uma _release branch_ é especialmente útil quando uma equipe não consegue manter a estabilidade na mainline, e serve como "filtro" para que o ambiente de produção seja menos afetado por tais instabilidades. 

- Também é possível criar mais de uma branch entre a _mainline_ e o branch de produção para que **adequações específicas para as configurações de ambiente** de cada cliente sejam aplicadas/testadas.

- Padrões com foco na produção possibilitam a criação de **hotfixes** para falhas mais graves, que necessitam de correção imediata em ambiente de produção.

**3. [Padrões básicos](https://martinfowler.com/articles/branching-patterns.html#LookingAtSomeBranchingPolicies)**

- **Padrões menores, menos complexos, que se utilizam menos de recursos como _release branches_ ou _hotfix branches_.

--------------------------------------------

**Adicionalmente, também temos os**

**4. [Padrões de apoio](https://martinfowler.com/articles/branching-patterns.html#OtherBranchingPatterns)**

- **Servem como apoio** para os padrões mencionados acima, podendo ser utilizados para fins de teste e apresentação de grandes mudanças de funcionalidade e interface, granularidade da _mainline_ de um projeto em "_sub-mainlines_", que são gerenciadas por cada equipe e adicionadas à mainline após um período maior de tempo,

**Comment by kyriosdata** [comment]
Você comentou as classificações dos padrões, a intenção eram os três padrões do grupo dos básicos. 

COM APROVEITAMENTO. 👍
