### ISSUE TITLE
T15

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#201]
A que eu considero mais simples é o [Github Flow](https://guides.github.com/introduction/flow/), cada funcionalidade (adições ou correções) em uma branch com nome não padronizado, abre-se o pull-request para a branch master, após revisão e correções da branch ela é mergeada com a master. Há apenas uma branch "compartilhada" que é a master

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
