### ISSUE TITLE
T16

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#202]
**Tarefa: 16**
**Padrões de base**

**1. Ramificação de fonte**

Nesse padrão é criado uma cópia onde se registra todas as alterações nessa cópia. Dessa forma, eu como desenvolvedor irei criar apenas uma branch onde colocarei todas as minhas alterações e realizarei o commit na master. O problema maior nesse tipo de ramificação é que pode haver vários conflitos quando pensamos que vários desenvolvedores irão realizar alterações que serão diretamente inseridas na master, exigindo assim, uma maior interação e comunicação entre esses.

**2. Linha principal**

Nesse padrão existe um único ramo compartilhado que atua como o estado atual do produto, ou seja, sempre que desejo iniciar um novo trabalho, puxo o código da linha principal para o meu repositório local para começar a trabalhar e sempre que quiser compartilhar meu trabalho com o restante da equipe, atualizarei essa linha principal com meu trabalho. Dessa forma, todo o trabalho é realizado na master do desenvolvedor e inserido diretamente na master central. Deve ser utilizada principalmente quando desejo que qualquer inicie rapidamente uma compilação atualizada do produto a partir da ponta da linha principal,  tornando mais fácil ver qual é o estado da base do código.

**3. Galho saudável**

Nesse padrão, em cada confirmação, executarei verificações automatizadas, geralmente criando e executando testes, para garantir que não haja defeitos no branch. Assim sendo, o foco é  manter um branch saudável onde ele é compilado com sucesso e o software é executado com poucos  bugs.
Para garantir isso, enquanto escrevemos o código de produção, também escrevemos um conjunto abrangente de testes automatizados para que possamos ter certeza de que, se esses testes passarem, o código não conterá bugs. Dessa forma, um commit só realizado quando meu código no branch é aprovado nos teste.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
