### ISSUE TITLE
T16

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#207]
**Tarefa: T16**
**Padrões básicos**

**1. Crie cópia e registre mudanças na cópia:**
> Acho bastante interessante fazer a leitura desse tipo de artigo, visto que iniciei minha carreira como desenvolvedor recentemente e faço uso de absolutamente todos esses padrões, principalmente esse primeiro, que pra mim é a base para os outros três. Seria praticamente impossível o desenvolvimento de software sem esse processo de criar uma cópia do "projeto" localmente, desenvolvê-la e em determinador momentos inserir eventuais mudanças no branch master, ou na "linha principal". Basicamente esse esse padrão nos diz que com base num linha principal, os vários desenvolvedores podem trabalhar localmente em suas maquinas, de modo a contribuir gradativamente para o desenvolvimento do software, penso nesse conceito como: dividir para conquistar. É claro que sem um software de controle de versão essa tarefa seria praticamente impossível.

**2. Um único branch compartilhado mantém o estado corrente do software:**
> O objetivo desse padrão é definir a maneira como desse ser desenvolvido um software usando uma "linha principal" de código, como por exemplo: a cada vez que eu iniciar um trabalho nessa linha principal, eu devo obter o código dela para uma maquina local, realizar as mudanças, e no momento oportuno, devo atualizar essa linha principal.

**3. A cada commit realize verificações automatizadas, em geral pelo uso de testes para assegurar ausência de defeitos no branch:**
> Esse ultimo padrão diz respeito à qualidade nesse processo de desenvolvimento e à qualidade no próprio software, visto que ele prima pela estabilidade e qualidade do código produzido/ alterado, com a aplicação de verificações e testes automatizados a para inserção e/ou modificação do código-fonte.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
