### ISSUE TITLE
T15

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#208]
**Tarefa: T15**

https://sites.google.com/site/alunopragmatico/conhecimentos-gerais-de-ti-desenvolvimento-e-infraestrutura/desenvolvimento-seguro-de-software

https://pt.wikipedia.org/wiki/Sistema_de_controle_de_vers%C3%B5es

http://homepages.dcc.ufmg.br/~dantas/GPSII/Slides-7-GerenciaDeConfiguracao.pptx

**Comment by willianjferreira** [comment]
ATIVIDADE ENTREGUE FORA DO PRAZO

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
