### ISSUE TITLE
T17

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#209]
1. No momento a branch `master`, e a branch `topico-17`
2. A branch `topico-17`
3. Cria uma nova branch `topico-17` se essa ainda não existir, se existir lança erro
4. Não porque após o `add` não foi feito o `commit`, nesse momento a branch `topico-17` no repo remoto é idêntica à master e o arquivo 17.md está em stage local
5. Não, a mensagem oficial no repositório não condiz com o comando
6. Mesmo que tenha concluído a quarta questão como na mensagem do commit, também é adicionada a quinta questão, que não é explicada na mensagem, portanto acredito que a mensagem não confere todas as mudanças
7. Não inclui
8.
9. Entendo e não concordo

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
