### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#21]
**Qual o objetivo do programa MPS.BR?**
O MPS.BR visa descrever de forma detalhada o MR-MPSSW e as definições comuns aos diversos documentos que compõem o MPS.BR.Este documento é destinado, mas não está limitado, a organizações interessadas em utilizar o MR-MPS-SW para melhoria de seus processos de software, Instituições Implementadoras (II), Implementadores Credenciados, Instituições Avaliadoras (IA) e outros interessados em processos de software, que pretendam conhecer e utilizar oMR-MPS-SW como referência técnica.

**Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**
Baseline

**O que é um projeto?**
Projeto é um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva.

**O que é produto de trabalho?**
É um artefato associado à execução de um processo.

**Qual o propósito do processo "Gerência de configuração"?**
O propósito do processo Gerência de Configuração é estabelecer e manter a integridade de todos os produtos de trabalho de um projeto e disponibilizá-los a todos os envolvidos.

**Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
São esperados 5 resultados,

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
