### ISSUE TITLE
Recursos git

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#215]
1) git init
2) git status 
3) git branch nome_na_branch
4) git checkout nome_da_branch
5)git remote add apelido_do_repositorio  endereço_do_repositorio
6) git remote -v
7) git add .
8) git commit -m "mensagem do commit"
9)git push apelido_repositorio nome_branch
10)git help 
11) git pull apelido_repositorio nome_da_branch
12)git merge nome-do-branch

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
