### ISSUE TITLE
Recursos Git

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#216]
git log - exibe o log dos commits
git add -A - adiciona todos os elementos não ignorados a stagging area
git commit -m "..." - realiza um commit com a mensagem "..."
git push <caminho-github> <branch>
git status - visualiza os elementos criados, modificados ou removidos que ainda não tenham sido commitados
git fetch - puxa do repositório remoto (github, gitlab...) as novas branches e commits realizados por outros colaboradores, inclusive na própria branch em uso.. Só que essa branch remota referente à mesma branch em uso não faz merge diretamente, vc precisa chamar o git merge manualmente para trazer os novos commits realizados na mesma branch.
git merge - agora que você já tem as novas branches atualizadas você pode realizar um merge de alguma branch na sua branch atual, assim atualizando seu estado.
git pull - é a junção do fetch com o merge, ele já atualiza e faz merge da branch remota, de mesmo nome da branch atual, na branch atual, portanto, atualizando seus arquivos.
git stash - retorna os arquivos não commitados ao estado do último commit válido. Muito bom pra desfazer algo que não funcionou bem e quebrou a aplicação a tempo de não enviar para o repositório remoto.
git remote add <apelido> <url_repositorio_remoto> - esse comando dá um apelido para a url do repositório remoto do projeto, evitando que o desenvolvedor precise digitar toda vez o caminho do repositório, bastando chamar seu apelido.

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
