### ISSUE TITLE
Recursos Git

### ISSUE THREAD

**Issue by lucianomenddes** [kyriosdata/git#221]
Comandos Git.
git config -- global user.name " "  -> Setar usuário
git config --global user.email " "  -> Setar email
git init        -> Criar novo repositório 
git status   -> Verificar estado dos arquivos/diretórios 
git add .      -> Adicionar todos arquivos/diretório no staged area
git clone     -> Clonar um repositório 
git commit  -> Comitar arquivo/diretório 
git log        -> Exibir histórico 
git rm  meu_arquivo.txt -> Remover arquivo
git rm -r diretorio -> Remover diretório 
git branch test    -> Cria uma nova branch chamada test
git checkout test  -> Trocando para uma branch existente
git branch -d test  -> Excluir um branch 
git pusch -> Enviar arquivos/diretório para o repositório remoto
git pull -> Atualizar os arquivos na branch atual

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
