### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by rodrigocoutinho** [kyriosdata/git#24]
**Tarefa: 02 - Atividades**
•	**Qual o objetivo do programa MPS.BR?**
Compatibilidade com os padrões de qualidade aceitos internacionalmente e que tenha como pressuposto o aproveitamento das boas práticas representadas nos padrões e modelos de melhoria de processo já disponíveis.

•	**Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**
Baseline [ISO/IEC/IEEE, 2017]

•	**O que é um projeto?**
Um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva [PMI, 2008]. 

•	**O que é produto de trabalho?**
Um artefato associado à execução de um processo [ISO/IEC, 2015a].

•	**Qual o propósito do processo "Gerência de configuração"?**
Estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos.

•	**Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
5, a partir do nível F.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
