### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by artiumdominus** [kyriosdata/git#27]
Meu nome: Pedro Basilio de Camargo Neto
Meu registro acadêmico: 201602511
Minha conta no GitHub: https://github.com/artiumdominus/gcs-2020-01

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Pedro, não se esqueça de complementar o tópico 01 e fazer os tópicos 02, 03, 04, 05 e 06. Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
