### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by pauloj2000** [kyriosdata/git#31]
**Qual o objetivo do programa MPS.BR?**

O objetivo é mehorar a capacidade de desenvolvimento de software nas empresas brasileiras.

**Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**

Baseline.

**O que é um projeto?**

Minha versão: É um esforço em determinado tempo para concretizar um plano em um produto, serviço, ou resultado. 

MPSBR: Um empreendimento realizado para criar um produto, serviço ou resultado
específico. O projeto se caracteriza por temporalidade e resultado, serviço ou
produto único e elaboração progressiva)

**O que é produto de trabalho?**

Um artefato associado à execução de um processo.

**Qual o propósito do processo "Gerência de configuração"?**

O propósito do processo Gerência de Configuração é estabelecer e manter a
integridade de todos os produtos de trabalho de um processo ou projeto e
disponibilizá-los a todos os envolvidos. 

**Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**

7 resultados esperados

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
