### ISSUE TITLE
Ambientação com a disciplina

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#38]
Minha única dúvida é sobre o calendário: até que dia vai o calendário da disciplina?
Não tenho mais nenhuma duvida.

**Comment by kyriosdata** [comment]
Rafael, a minha expectativa é que se encerre até o dia 31 de dezembro, dia a partir do qual estou de férias compulsórias (é importante que o @willianjferreira  também tenha conhecimento). Contudo, a UFG já possui um calendário vigente, onde as aulas podem se estender até o início do próximo ano. Vamos ter que aguardar um pouco mais para ter uma previsão, ok? 

COM APROVEITAMENTO. 👍
