### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by trete** [kyriosdata/git#40]
•Qual o objetivo do programa MPS.BR?
O programa MPS.BR é aumentar a competitividade das organizações por meio da melhoria de seus processos.

•Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?
O nome é baseline.

•O que é um projeto?
A definição de projeto é "um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva".

•O que é produto de trabalho?
É um artefato relacionado (usado, produzido, ou alterado por) a execução de um processo.

•Qual o propósito do processo "Gerência de configuração"?
O propósito do processo Gerência de Configuração é estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos.

•Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?
Estão definidos cinco resultados esperados.

**Comment by kyriosdata** [comment]
- Melhor seria: "O objetivo do programa MPS.BR..."

COM APROVEITAMENTO. 👍
