### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#41]
Qual o objetivo do programa MPS.BR?
R. O objetivo é o aumento da competitividade das organizações através da melhoria dos seus processos.

Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?
R. Baseline (ISO/IEC/IEEE, 2017)

O que é um projeto?
R. Um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva (PMI, 2008)

O que é produto de trabalho?
R. Um artefato associado à execução de um processo (ISO/IEC, 2015a).

Qual o propósito do processo "Gerência de configuração"?
R. Estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos.

Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?
R. São 5 resultados esperados:
	* Itens de configuração são identificados e seus níveis de controle são estabelecidos
	* Um sistema para gerência de configuração e controle de mudanças é estabelecido, mantido atualizado e utilizado.
	* Baselines são estabelecidas considerando entregáveis e liberações aos interessados.
	* Registros de itens de configuração e de modificações realizadas nestes itens são estabelecidos, mantidos atualizados e utilizados.
	* Auditorias de configuração são executadas para avaliar as baselines e o conteúdo do sistema de gerência de configuração

**Comment by kyriosdata** [comment]
COM APROVEITAMENTO. 👍
