### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#43]
### **Seguem questões e respectivas respostas:** 

**1. Qual o objetivo do programa MPS.BR?**
O objetivo do programa MPS.BR é o aumento da competitividade das organizações
pela melhoria de seus processos.

**2. Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**
Baseline.

**3. O que é um projeto?**
É um empreendimento realizado para criar um produto, serviço ou resultado
específico. O projeto se caracteriza por temporalidade e resultado, serviço ou
produto único e elaboração progressiva.

**4. O que é produto de trabalho?**
É um resultado útil de um processo.

**5. Qual o propósito do processo "Gerência de configuração"?**
O propósito do processo Gerência de Configuração é estabelecer e manter a
integridade de todos os produtos de trabalho de um processo ou operação do
serviço e disponibilizá-los a todos os envolvidos

**6. Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
São 8 resultados esperados.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
