### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by jhordangab** [kyriosdata/git#45]
Qual o objetivo do programa MPS.BR?

	O aumento da competitividade das ogranizações pela melhoria de seus processos

Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?

	Baseline

O que é um projeto?

	Um empreendimento realizado para criar um produto, serviço ou resultado específico.

O que é produto de trabalho?

	Um resultado útil de um processo

Qual o propósito do processo "Gerência de configuração"?

	Estabelecer e manter a integridade de todos os produtos de trabalho de um processo ou operação do serviço e disponibilizá-los a todos os envolvidos

Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?

	São 8 resultados esperados

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
