### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by jhordangab** [kyriosdata/git#46]
1 - Acessar o link para a pesquisa avançada

2 - Montar a pesquisa com os seguintes atributos:

is:issue [Informando que o que deseja buscar é uma issue]
"stringdebusca" in:title [String que está presente no título da issue desejada]
author:nomedoautor [Autor da issue]
repo:nomedorepositorio [Repositório onde a issue se encontra]

Como exemplo a seguinte busca avançada:

is:issue "disciplina" in:title author:jhordangab repo:kyriosdata

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
