### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by cleydsonjr** [kyriosdata/git#49]
**1. Qual o objetivo do programa MPS.BR?**

O objetivo do programa MPS.BR é o aumento da competitividade das organizações promovendo a melhoria dos seus processos.

**2. Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**

Baseline (ISO/IEC/IEEE, 2017)

**3. O que é um projeto?**

Um projeto é um esforço temporário para realizar um resultado.
De acordo com o PMI, é um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva

**4. O que é produto de trabalho?**

Um artefato associado à execução de um processo (ISO/IEC, 2015a).

**5. Qual o propósito do processo "Gerência de configuração"?**

O propósito do processo "Gerência de Configuração" é estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los aos envolvidos.

**6. Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
São 5 resultados esperados: GCO 1, GCO 2, GCO 3, GCO 4 e GCO 5

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
