### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by augustobmoura** [kyriosdata/git#50]
**Qual o objetivo do programa MPS.BR?**
> O objetivo do programa MPS.BR é o aumento da competitividade das organizações pela melhoria de seus processos

**Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**
> Se chama baseline

**O que é um projeto?**
> Um projeto é um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva

**O que é produto de trabalho?**
> É um item/artefato produzido pela execução um processo

**Qual o propósito do processo "Gerência de configuração"?**
> O propósito é estabelecer e manter a integridade dos produtos de trabalho de um processo e disponibilizá-los a todos os envolvidos

**Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
> 5 resultados esperados

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
