### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by lucianomenddes** [kyriosdata/git#51]
• Qual o objetivo do programa MPS.BR? 
	
              O objetivo do programa MPS.BR visa incentivar o aumento da competitividade das organizações pela melhoria do seus processos de projeto e organizacionais. Seguindo as duas metas a serem alcançadas , meta técnica e a meta de negócio.
E que os modelos MPS seja adequado para  diferentes perfis de empresas seja privada, governamentais , tendo uma atenção maior para empresas medias , pequenas e micro. É objetivo também do programa MPS que os modelos sejam compatíveis com os padrões de qualidade aceitos internacionalmente e que tenha como pressuposto aproveitamento das boas práticas nos padrões e modelos de melhoria de processo.   
   
   • Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?
	   
	 O nome é baseline 
		
    • O que é um projeto?
	     É um empreendimento caracterizado por temporalidade para realizar a criação de um produto , serviço ou algum resultado especifico.
		
    • O que é produto de trabalho?
	     Um artefato produzido que está associado à execução de um processo que pode ser usado e alterado pelo o processo.
	
    • Qual o propósito do processo "Gerência de configuração"? 
                O  processo de gerência de configuração da suporte para  todas as fases  do ciclo de vida do desenvolvimento de software, fazendo a rastreabilidade dos itens de configuração desde a especificação dos requisitos do sistema  e controlando as modificações por meios  de método e ferramentas para   maximizar a produtividade e minimizar os erros durante a evolução do software .
               
    • Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?
	   São três resultados principais do processo de gerência de configuração , controle de modificação , controle de versão e gerenciamento de construção.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
