### ISSUE TITLE
Busca Avançada

### ISSUE THREAD

**Issue by rafareisbr** [kyriosdata/git#53]
Para que eu possa buscar todas as issues criadas por mim, com status "fechada" neste repositório a barra de busca deverá estar preenchida com os seguintes dizeres: repo:kyriosdata/git author:rafareisbr state:closed

**Não sei se entendi. Caso eu não tenha atendido ao que pretendia ser avaliado é só comentar aqui que eu corrijo o que for necessário.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍

**Comment by willianjferreira** [comment]
Rafael, não se esqueça de fazer os tópicos 04, 05 e 06.  Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
