### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by trete** [kyriosdata/git#54]
Para realizar uma busca no github para listar todas as issues com um certo título, criadas por determinado usuário, em um dado repositório, pode-se acessar https://github.com/search/advanced, e digitar o título a ser buscado, seguido de "repo: <nome do usuário que criou o repositório>/<nome do repositório> ", e adicionar "author: <nome do autor> ".
Realizar a busca avançada te direcionará a uma página que oferece várias listas de resultado de tipos diferentes. Para encontrar as issues, basta selecionar "issues" no menu à esquerda da página.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
