### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#56]
1)Qual o objetivo do programa MPS.BR?
R: determinar e aprimorar um modelo para melhoria e avaliação dos processos e serviços correlatos, tento como preferencia micro, pequenas e médias empresas, com o intuito de tornar essas organizações conhecidas nacional e internacionalmente como sendo um modelo aplicável à indústria de software

2)Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?
R: Artefato

3)O que é um projeto?
R:Um projeto é um esforço temporário empreendido para criar um produto, serviço ou resultado exclusivo

4)O que é produto de trabalho?
R:Um Produto de Trabalho é uma abstração geral que representa algo resultante do processo.  Os Produtos de Trabalho incluem:Artefato,distribuível,resultado

5)Qual o propósito do processo "Gerência de configuração"?
R: gerenciar os artefatos produzidos durante o projeto bem como seus ciclo de vida, independente de seu tipo de mídia, fornecendo informações e recursos de gerenciamento de todos os artefatos gerados durante o projeto , controlando não apenas o versionamento do projeto como também sua vida útil.
"O propósito do processo Gerência de Configuração é estabelecer e manter a integridade de produtos de trabalho e disponibilizá-los a todos os envolvidos."

6)Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?
R: 5 resultados esperados GCO 1,GCO 2,GCO 3,GCO 4,GCO 5

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO 👎

**Comment by willianjferreira** [comment]
LUCAS, Não se esqueça de reabrir o tópico 02. Está fechado SEM APROVEITAMENTO (pois foi entregue fora do prazo). **Reabra e deixe aberto**. Eu ou o Professor Fábio faremos o novo fechamento e registraremos na planilha de controle.
