### ISSUE TITLE
busca avançada

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#57]
Pode-se listar/filtrar todas as issues com um titulo especifico, criada por um especifico user em um repositório determinado acessando  https://github.com/search/advanced, lá você terá acesso a vários itens de filtro de busca para refinar sua pesquisa.
para a pesquisa especifica acima deve-se  digitar o título a ser pesquisado, seguido de "repo: <user name >/<nome do repositório> ", e adicionar "author da issue: , a ferramenta oferece outros filtros de busca , para uma busca ainda mais refinada

"ambientaçao com a disciplina user:kyriosdata repo:git fullname:lucasnshunter"

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO 👍
