### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#58]
1-Para realizar a consulta de todas as issues criadas por mim no repositório  https://github.com/kyriosdata/git, foi necessário acessas a busca avançada:  https://github.com/search/advanced, conforme recomendado na descrição do Tópico 03. 

2-Na sequência eu adicionei no campo **"Advanced options -> In these repositories"** o repositório: kyriosdata/git, que é utilizado nessa disciplina.

3-Em seguida em **"Issues options-> In the state"**, deixei como padrão para buscar as issues abertas e as fechadas, ou seja: todas a issues do repositório kyriosdata/git. 

4-Por fim eu adicionei o ultimo filtro no campo **"Issues options-> Opened by the author"**, o meu nome de usuário: mcocampos.

### **Resultado:** 
Exibição de todas as 4 issues criadas por mim no momento da consulta.
**Resultado na URL:** https://github.com/search?q=repo%3Akyriosdata%2Fgit+author%3Amcocampos&type=Issues&ref=advsearch&l=&l=
**Resultado no campo de pesquisa:** repo:kyriosdata/git author:mcocampos

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
