### ISSUE TITLE
Meu Repositório

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#62]
**Tarefa: T01**
**Meu nome:** Marcos Mathias Pereira
**Meu registro acadêmico:** 201508740
**Minha conta no Github:** https://github.com/marcosmathias/gcs-2020-01

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by marcosmathias** [comment]
Oi Willian,

Conforme T07, solicito reabertura e verificação do aproveitamento da tarefa.

Obrigado!

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
