### ISSUE TITLE
Minhas dúvidas

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#63]
**Tarefa: T01**
Não tenho nenhuma dúvida até o momento.

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by marcosmathias** [comment]
Oi Willian,

Conforme T07, solicito reabertura e verificação do aproveitamento da tarefa.

Obrigado!

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
