### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by kayo08** [kyriosdata/git#64]
O objetivo do MPS.BR é utilizado para melhorar os processos de serviços, instituições implementadoras, instituições avaliadoras e outros interessados em processos de serviços, que pretendam conhecer e utilizar o MR-MPS-SV como referencia técnica.

Baseline é nome que se dá a uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração.

Projeto é um empreendimento realizado para criar um produto, serviço ou resultado especifico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva.

Produto de Trabalho é o resultado útil de um processo.

O propósito da Gerência de Configuração é estabelecer e manter a integridade de todos os produtos de trabalho de um processo ou operação do serviço e disponibiliza-los a todos os envolvidos.

São esperados 8 resultado da Gerencia de Configuração.

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by kayo08** [comment]
Reabrindo Tópico!
