### ISSUE TITLE
Ambientação com a disciplina

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#65]
**Tarefa: T02**
I. **Qual o objetivo do programa MPS.BR?**
O objetivo do programa MPS.BR é o aumento da competitividade das organizações pela melhoria de seus processos, com modelos MPS (Plano Mestre de Produção) que sejam adequados ao perfil de empresas com diferentes tamanhos e características, privadas e governamentais.

II. **Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?**
Baseline.

III. **O que é um projeto?**
Projeto é um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva.

IV. **O que é produto de trabalho?**
Um resultado útil de um processo.

V. **Qual o propósito do processo "Gerência de configuração"?**
O propósito do processo Gerência de Configuração é estabelecer e manter a integridade de todos os produtos de trabalho de um processo ou operação do serviço e disponibilizá-los a todos os envolvidos

VI. **Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?**
Oito resultados esperados, sendo eles:
- GCO 1. Um Sistema de Gerência de Configuração é estabelecido e mantido;
- GCO 2. Os itens de configuração são identificados com base em critérios estabelecidos;
- GCO 3. Os itens de configuração sujeitos a um controle formal são colocados sob baseline;
- GCO 4. A situação dos itens de configuração e das baselines é registrada ao longo do tempo e disponibilizada;
- GCO 5. Modificações em itens de configuração são controladas;
- GCO 6. O armazenamento, o manuseio e a liberação de itens de configuração e baselines são controlados;
- GCO 7. Auditorias de configuração são realizadas objetivamente para assegurar que as baselines e os itens de configuração estejam íntegros, completos e consistentes;
- GCO 8. As informações de itens de configuração são comunicadas às partes interessadas;

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by marcosmathias** [comment]
Oi Willian,

Conforme T07, solicito reabertura e verificação do aproveitamento da tarefa.

Obrigado!

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
