### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by kayo08** [kyriosdata/git#67]
Para listar as issue através da busca avançada primeiramente ir em [https://github.com/search/advanced](url).

- Preencher os campos para encontrar o que deseja, no caso fiz um busca para listar as issue criadas ate o momento:
   Owners: kyriosdata
   Repositories: git
   Issue state: open/close
   Author: kayo08

Assim foi listada as 4 issue feitas por mim.

![image](https://user-images.githubusercontent.com/21229454/93140965-b8eace00-f6b9-11ea-8479-e181970ceee6.png)

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
