### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#69]
**Tarefa: 03**

Entre na tela de pesquisas avançadas https://github.com/search/advanced, vá até a opção "Issues options" e preencha os campos conforme necessidade, sendo que, em
 "In the state" escolha se o estado é aberto, fechado ou ambos;
"With this many comments", determine a quantidades de comentários, podendo ser de 0...100, < ou > que determinado valor;
"With the labels", defina o label que a issue deve conter(bug,tarefa,etc)
"Opened by the author", determine o autor da issue;
"Mentioning the users", determine os usuários que foram mencionados na issue, caso tenha.
"Assigned to the users", caso saiba para qual usuário foi assinado a issue, poderá colocar nessa campo;
"Updated before the date", coloque até que data as issue's foram criadas, exemplo: <2020-09-14.
Depois de preenchidos os campos, clique "Search" disposto no lado direito superior da tela.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
