### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#72]
**Tarefa: 04**
**Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.**
estabelecer: determinar os itens que serão colocados na gerência de configuração;
manter: garantir a permanência de todos os produtos de trabalho;
integridade: garantir a corretude do produto de trabalho, de acordo com o que foi planejado e realizado.
produtos de trabalho:Um artefato associado à execução de um processo.
projeto:Um empreendimento realizado para criar um produto, serviço ou resultado específico.
disponibilizá-los: permitir que os produtos de trabalho seja acessível para todos os interessados/envolvidos.
envolvidos: todos os interessados no produto de trabalho, sendo esses indivíduos ou organização impactados produtos de trabalho e seus autores e gerenciadores. 
**Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.**
O propósito da Gerência de Configuração é permitir definir e gerenciar todos os itens de configuração, possibilitando que esses sejam corretos durante todo o processo de produção do sw, garantido o controle, verificação e validação da integridade desses itens e das mudanças  no sistema de GCO.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
