### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by ThallysonNK** [kyriosdata/git#73]
Pesquisar por, TÍTULO user:thallysonnk repo:kyriosdata/git ou somente TÍTULO user:thallysonnk, se estiver na página do repositório, e clicar na aba Issues.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Thallyson, não se esqueça de fazer os tópico 02, 04, 05 e 06. Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
