### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by wesleywrl** [kyriosdata/git#74]
**Tarefa: 05**
**Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**
Sim, podemos ter um ou vários arquivo dentro de um item de configuração, já que esse pode ser uma especificação ou um código fonte.

**Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**
Sim, todos os itens devem conter um identificador único, sendo esse um resultado esperado do processo de GCO. O resultado esperado seria a formação da baseline.

**Uma issue no Github pode ser considerada um item de configuração?**
Sim, já que esse é um artefato produzido durante a produção de sw.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
