### ISSUE TITLE
Busca avançada

### ISSUE THREAD

**Issue by lucianomenddes** [kyriosdata/git#76]
**Listar todas as issues com um determinado título (opcional), criada por determinado usuário, em um dado repositório.**

As restrições montada pela a pesquisa avançada ficaram na seguinte formato ->   **user:lucianomenddes repo:kyriosdata/git  author:lucianomenddes state:closed**

Para pesquisar por uma determinada issues basta colocar o título  na frente da propriedade "author" por exemplo
**user:lucianomenddes repo:kyriosdata/git  ambientação com a disciplina author:lucianomenddes state:closed**
caso a issues se encontra no estado aberto só alterar a propriedade " state" para open.

Descrições das propriedades de restriçõe de pesquisa usadas na pesquisa acima
user -> nome do usuário
repo-> repositorio onde será feito a pesquisa 
author-> autor da issues
state-> informar em qual estado da issues para a pesquisa aberto ou fechedo 

OBS:
As pesquisas avançadas podem ser feita atravez da interface grafica preenchendo os inputs de restrições em https://github.com/search/advanced e também pode ser feita direta com os parâmetros de restrições no input de pisquisa que fica no header da pagina do  github.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
