### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by jhordangab** [kyriosdata/git#77]
"Gerência de Configuração (GCO), ou ainda Software Configuration Management (SCM), tem como propósito estabelecer e manter a integridade de todos os produtos de trabalho de um projeto e disponibilizá-los a todos os envolvidos".

- Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles:

ESTABELECER:
Definição dos ítens que serão colocados na GCO
MANTER:
Garantir a integridade de todos os produtos de trabalho
INTEGRIDADE:
Assegurar que os produtos de trabalho tenham suas características preservadas
PRODUTOS DE TRABALHO:
Resultado da execução de um processo
PROJETO:
Descrição escrita e detalhada de um empreendimento a ser realizado
DISPONIBILIZÁ-LOS:
Acessibilidade do produto para todos os envolvidos
ENVOLVIDOS:
Partes interessadas

- Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.

Aplicar o processo desde a fase de definição até a parte da entrega a todos os envolvidos no projeto, onde todos os artefatos devem estar disponíveis e de maneira integra.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
