### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#78]
1) Estabelecer : Criar a cultura , implantar
2) Manter: Uma vez criado a diretriz , manter a execução da mesma
3) Integridade: Garantia de que o "produto de trabalho" esteja integro ou seja que o mesmo esteja de acordo com seu conceito no momento de sua criação e que o mesmo não foi corrompido e caso tenha sido alterado o mesmo deve ter notificação e documentação de tal evento.
4) Produtos de trabalho: Coisas produzidas , artefatos produzidos no projeto(Um artefato associado à execução de um processo ).
5) Projeto: Um empreendimento realizado para criar um produto, serviço ou resultado
específico. O projeto se caracteriza por temporalidade e resultado, serviço ou
produto único e elaboração progressiva
6) Disponibilizá-los: Deixar algo disponível aos interessados/interessados do projeto desde que os mesmos tenham autorização para tal.
7) Envolvidos: atuantes e passivos interessados no projeto que interagem com os produtos de trabalho em alguma etapa do processo

Proposito da GCO: Proposito é controlar o que foi produzido ,garantindo sua integridade , e organizar tudo corretamente para que esteja acessível a quem precisar/interessar , desde que tenha permissão de acesso a tal artefato.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
