### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#79]
**Tarefa: T04**
Ambientação com gerência de configuração (MPS.BR)

_Com base no próposito deste processo conforme o MPS.BR: "Gerência de Configuração (GCO), ou ainda _Software Configuration Management_ (SCM), tem como propósito **estabelecer** e **manter** a **integridade** de todos os **produtos de trabalho** de um **projeto** e **disponibilizá-los** a todos os **envolvidos**"._

**1. Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.**
- **Estabelecer**: Definir. instituir. Neste contexto, devemos estabelecer a integridade de tudo aquilo o que for produzido dentro de um projeto.
- **Manter**: Firmar, estabilizar. Neste contexto, devemos estabilizar a integridade dos produtos, sem que haja redução/comprometimento da mesma após a entrega.
- **Integridade**: Consolidação. É o que define se os produtos de um projeto são disponibilizados de forma estável e precisa.
- **Produtos de Trabalho**: São os resultados finais do projeto a serem entregues para o cliente, incluindo todos os artefatos (a documentação do projeto, o próprio software, dentre outros).
- **Projeto**: Um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva.
- **Disponibilizá-los**: Tornar o acesso aos Produtos de Trabalho possível para todas as partes envolvidas.
- **Envolvidos**: Todos os envolvidos no projeto.

**2. Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.**
- A Gerência de Configuração, de acordo com o MPS.BR, é responsável por garantir que tudo aquilo o que foi produzido durante um projeto seja entregue e disponibilizado de forma confiável e estável para todas as partes envolvidas.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
