### ISSUE TITLE
Item de configuração 

### ISSUE THREAD

**Issue by lucianomenddes** [kyriosdata/git#80]
**Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**

Os item de configuração são identificado de maneira única  e podem estar relacionados a outros item de configuração e sua  evolução é possível de ras­treamento. O controle da Gerência de Configuração será feito sobre estes itens e serão mantidas todas as informações a seu respeito.  Diversas  versões  de  um  mesmo  item de configuração  podem  existir como produto das modificações efetuadas no dia­a ­dia.

**Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**

Sim, todo item de configuração deve possuir um identificador único . O resultado espera do processo de GCO será agrupar um conjunto de todos  item de configuração com as mais novas versões e criar a baseline. 

**Uma issue no Github pode ser considerada um item de configuração?**
Sim, pois possui identificador único é um artefato produzido durante o processo.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
