### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#81]
**i-Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.**

> **Itens de Configuração:** Produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração. Os itens de configuração sujeitos a um controle formal são colocados sob baseline;
> **Sistema para Gerência de Configuração:** Um Sistema de Gerência de Configuração é estabelecido e mantido;
> **Baseline:** Uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração.
> **Auditoria de configuração:** são realizadas objetivamente para assegurar que as baselines e os itens de configuração estejam íntegros, completos e consistentes;
> **Processos Organizacionais:** são os processos concebidos para fornecer os recursos necessários para que o projeto/serviço atenda às expectativas e necessidades das partes interessadas da organização. 
> **Gerência de Processos:** estabelece, mantem atualizado, identifica e realiza melhorias em um conjunto de ativos de processo da organização e padrões do ambiente de trabalho usáveis e aplicáveis às necessidades de negócio da organização.

**ii-Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.**
> Ao meu ver, o processo de gerência de configuração, desde que seja bem executado, garante que que o produto de software a ser entregue seja disponibilizado em sua completude, para as pessoas ou organizações que tem por objetivo seu uso, estudo ou evolução. Observando os prazos definidos entre as partes envolvidas no processo.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
