### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by mcocampos** [kyriosdata/git#82]
**Tarefa: T05**

**Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**
> Sim, podemos ter um único arquivo como item de configuração, e também um conjunto de arquivos também pode ser visto como sendo um item de configuração, pois esse conjunto pode ser controlado e tratado como uma entidade única no processo de gerência de configuração.

**Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**
> Sim, conforme a definição disponível na wikipedia, todo item de configuração deve possuir um identificador único. Sim, é um resultado esperado. GCO 1 -  Itens de configuração são identificados e seus níveis de controle são estabelecidos.

**Uma issue no Github pode ser considerada um item de configuração?**
> Sim, mas somente quando ela se for tratada como sendo um produto de trabalho designado para ser controlado e tratado
como uma entidade única no processo de gerência de configuração, que é a definição de IC.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
