### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by lucasnshunter** [kyriosdata/git#84]
1)Podemos ter um único arquivo como item de configuração? 
R:Sim podemos.
1.1)Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?
R:sim também pode
Referência = "Em função da granularidade utilizada em um contexto de serviços, um item de
configuração pode ser formado por um conjunto de artefatos ou componentes, bem
como um único artefato ou componente pode ser formado por vários itens de
configuração. "-https://www.softex.br/wp-content/uploads/2013/07/MPS.BR_Guia_de_Implementacao_SV_Parte_2_20132.pdf

2)Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único?
R:sim deveria;
2.1)Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?
R:Sim é um dos resultados esperados:
referencia-"(A partir do nível F) Itens de configuração são identificados e seus
níveis de controle são estabelecidos.
NOTA: (item requerido) Devem ser identificados itens de configuração tanto em
nível de projeto/serviço quanto organizacional."
3)Uma issue no Github pode ser considerada um item de configuração?
R: Não encontrei nenhuma referência formal que sustente essa afirmação, por isso digo que não. Complementando o argumento imagino que a issue tem função de ser um "tópico de discução" ou coisa equivalente, ela por si só, não é um item de configuração/produto de trabalho do projeto, entretanto acredito que ela possa dar origem a um ou que podemos colocar um dentro de uma issue de maneira informal, mas formalmente falando re-afirmo minha resposta de que issue não são classicamente itens de configuração

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
