### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by trete** [kyriosdata/git#85]
•Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?
Sim, um único arquivo pode ser tido como um item de configuração, e sim, um item de configuração pode reunir dezenas de arquivos. Contanto que ,dentro do contexto de seus projetos, um único arquivo ou um grupo de várias classes possam ser tratados como entidades únicas no processo de gerência de configuração, ou seja, depende do escopo e dos requisitos do projeto.

•Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?
Segundo a definição disponível na wikipedia, todo item de configuração deve ter um identificador único, e esse é um resultado esperado do processo de GCO (MPS.BR) do nível F, expressado precisamente no documento da seguinte forma: "(A partir do nível F) Itens de configuração são identificados e seus níveis de controle são estabelecidos."

•Uma issue no Github pode ser considerada um item de configuração?
Uma issue no github pode ser considerada um item de configuração, assim como qualquer produto de trabalho que precise ser controlado tratado como uma entidade única no projeto, não muito diferentemente da documentação tipicamente gerada em projetos de software.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
