### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by jhordangab** [kyriosdata/git#87]
**Tarefa: 05**

Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?

R: Sim, podemos ter um único arquivo ou um ítem que reúne vários arquivos, porém deve ser tratado como uma entidade singular pelo processo  de gerência de configuração;

Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?

R: Sim, segundo o wikipedia "a entidade deve ser identificada unicamente de modo que ela possa ser distinguida de todos os outros itens de configuração". 
Sim, é o resultado "GCO 2. Os itens de configuração são identificados com base em critérios estabelecidos";

Uma issue no Github pode ser considerada um item de configuração?

R: Sim, pois possui um identificador único e é gerado como um produto de trabalho durante o processo de gerência de configuração;

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
