### ISSUE TITLE
Meu repositório

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#88]
Meu nome: Pedro Henrique Pires de Jesus
Meu registro acadêmico: 201515577
Minha conta no Github: https://github.com/pedropirescg/gcs-2020-01

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by kyriosdata** [comment]
Corrigido, mesmo sem necessidade, pela #124 

COM APROVEITAMENTO. 👍
