### ISSUE TITLE
Tópico 02

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#90]
**Tarefa: top2/GCO**

1. Qual o objetivo do programa MPS.BR?

O modelo de qualidade MPS.BR foi criado com o objetivo de evoluir o ambiente de tecnologia no Brasil em diversos aspectos do desenvolvimento de software, como melhoria nos processos, métricas de qualidade e gestão, dentre vários benefícios que trazem ao resultado final softwares de melhor qualidade além de impulso a inovação e competitividade no mercado.

2. Qual o nome que se dá a "uma versão formalmente aprovada de um item de configuração, independente de mídia, formalmente definida e fixada em um determinado momento durante o ciclo de vida do item de configuração"?

Baseline

3. O que é um projeto?

De acordo com o Project Management Institute (PMI-2008), projeto é um empreendimento realizado para criar um produto, serviço ou resultado específico. O projeto se caracteriza por temporalidade e resultado, serviço ou produto único e elaboração progressiva. 

4. O que é produto de trabalho?

De acordo com o [SEI, 2010b], produto de trabalho é o resultado útil de um processo. Entendo como resultados úteis aquilo que extraímos dos processos realizados que são relevantes e aproveitáveis no desenvolvimento do software. Considerando que o desenvolvimento envolva não apenas a codificação mas todas suas etapas. Desde o levantamento de requisitos e metodologias aplicadas à implantação e manutenção da aplicação.

5. Qual o propósito do processo "Gerência de configuração"?

O motivo geral da execução de um processo de Gerência de Configuração é estabelecer e manter a integridade de todos os produtos de trabalho de um processo ou operação do serviço e disponibilizá-los a todos os envolvidos.

6. Quantos resultados esperados estão definidos para o processo de "Gerência de configuração"?

 - Foi estabelecido e mantido um sistema de gerência de configuração;
 - A identificação dos itens de configuração tenha baseada em critérios estabelecidos;
 - Quando em controle formal, os itens de configuração tenham sido colocados sob baseline;
 - A situação dos itens de configuração e das baselines tenha sido registrada e disponibilizada ao longo do tempo;
 - Todas as modificações nos itens de configuração tenham sido controladas, assim como o armazenamento, manuseio e liberação destes itens e baselines;
 - Tenha sido realizadas auditorias de configuração com objetivo de assegurar integridade, completitude e consistência das baselines e dos itens de configuração;
- Todas as partes interessadas tenham sido comunicadas das informações dos itens de configuração.

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:
