### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by kayo08** [kyriosdata/git#92]
i - 
Estabelecer: É a etapa onde e determinados os produtos e o que será utilizado no projeto
Manter: É a parte responsável por deixar o produto sempre estável até mesmo depois de finalizado
Integridade: Define o quão estável e acurado o projeto está
Projeto: é a conjunto de serviços e trabalho realizados para se ter um produto.
Disponibilizar: é a parte onde se é entregue o produto do projeto após concluído
Envolvidos: são as partes que estão ligadas ao projeto, seja ele cliente ou o que fornece o serviço.

ii - Gerencia de configuração seria um conjunto de metas para se obter e entregar o produto/software dentro dos conformes do controle de qualidade.

**Comment by willianjferreira** [comment]
SEM APROVEITAMENTO :-1:

**Comment by kayo08** [comment]
Reabrindo Tópico!

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
