### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by kayo08** [kyriosdata/git#93]
i - Sim, pode tanto ser um arquivo único como uma relação de configuração composto por vários arquivos. Mas o resultado de ambas deverão ser tratos como uma única entidade do processo

ii - A afirmação fornecida pelo Wikipédia esta correta, todo item de configuração (IC) deve possuir um identificador. No MPS.BR trata-se do resultado esperado GCO2 "A identificação dos ICs constitui em um momento crítico para o sucesso do processo
Gerência de Configuração na organização."

iii - Uma issue pode ser considerado um IC pois possui  identificadores e ser produto do trabalho do projeto.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
