### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by marcosmathias** [kyriosdata/git#94]
**Tarefa: T05**
Ambientação com gerência de configuração (MPS.BR)

**1. Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**
- Sim, podemos ter um único arquivo como item de configuração. É possível ter um item de configuração que reúne vários arquivos diferentes, desde que esse item seja tratado como uma entidade singular no processo de Gerência de Configuração. 

**2. Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**
- De acordo com a definição do artigo na Wikipédia para Item de Configuração, sim, todo item de configuração precisa ter um identificador único. O processo de GCO também espera que tal identificação seja realizada, tendo como resultado uma identificação feita por critérios preestabelecidos.

**3. Uma issue no Github pode ser considerada um item de configuração?**
- Uma issue no Github pode ser considerada um item de configuração por ser parte da documentação do desenvolvimento de um software.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
