### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by murilloandrade** [kyriosdata/git#95]
**1 - Conforme o MPS.BR, "item de configuração é o produto de trabalho designado para ser controlado e tratado como uma entidade única no processo de gerência de configuração". Podemos ter um único arquivo como item de configuração? Podemos ter um item de configuração que reúne vários arquivos, por exemplo, dezenas de classes Java, ou Javascript, por exemplo?**

Sim, tanto arquivos únicos quanto conjuntos de arquivos podem ser itens de configuração, sendo os arquivos únicos tratados com critérios diferentes dos conjuntos de arquivos e classes.

**2 - Leia a definição de item de configuração oferecida pela wikipedia. Segundo a definição disponível na wikipedia todo item de configuração deve possuir um identificador único? Este é um dos resultados esperados do processo de GCO (MPS.BR)? Se afirmativo, qual seria o resultado?**

Sim, todo item deve ter sua própria identificação para ser distinguido de outros itens. Esse conjunto de itens unicamente identificado, essa base, é um resultado esperado do processo de GCO.

**3 - Uma issue no Github pode ser considerada um item de configuração?**

Elas podem ser sim consideradas como itens de configuração, tanto como o processo de reconhecimento do problema quando o processo de manutenção do problema.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Murillo, não se esqueça de fazer os tópico 02, 03 e 04.  Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
