### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by rodrigocoutinho** [kyriosdata/git#97]
I - Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles.
1 - criar ou implantar um solução existente.
2 - manter toda estrutura em funcionamento.
3 - garantia que o artefato não foi alterado de maneira que não corresponda ao seu objetivo.
4 - resultado de um processo ou tarefa que resulte em um ou mais artefatos.
5 - um empreendimento realizado para criar um produto, serviço ou resultadoespecífico. 
6 - os artefatos devem estar disponíveis aos interessados.
7 - interessados e ligados a alguma parte ou resultado do projeto.

II - Criar e manter um ambiente para administrar e controlar os artefatos gerados no projeto e garantir que estejam disponíveis aos interessados.

Justificativa via email

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Rodrigo, não se esqueça de complementar o tópico 05 e fazer o tópico 06.  Conforme o tópico 07, é a oportunidade de reabrir e refazer (ou fazer) dentro do novo prazo.
