### ISSUE TITLE
Item de configuração

### ISSUE THREAD

**Issue by rodrigocoutinho** [kyriosdata/git#98]
1 - Sim, um item de configuração pode ser um unico arquivo, assim como pode conter varios outros arquivos, no escopo do projeto. Desde de que seja possivel identificar o artefato produzido.

2 - Sim, Os itens de configuração possuem um identificador único. É uma parte fundamental para o processo de gerência de configuração. Segundo MPS.BR resultado esperado: GCO 2 - (A partir do nível G) Um sistema para gerência de configuração e
controle de mudanças é definido, mantido atualizado e utilizado.

3 - Sim, se considerarmos o conteúdo da issue ou seja um artefato gerado em uma ou mais etapas do projeto.

Justificativa via email com relação a data

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:
