### ISSUE TITLE
GCO

### ISSUE THREAD

**Issue by pedropirescg** [kyriosdata/git#99]
**Tarefa: GCO/GCS**

"Gerência de Configuração (GCO), ou ainda Software Configuration Management (SCM), tem como propósito estabelecer e manter a integridade de todos os produtos de trabalho de um projeto e disponibilizá-los a todos os envolvidos". 

1. Esta definição faz uso de sete (7) conceitos relevantes para a compreensão de GCO. Defina cada um deles. 

Os itens de configuração são identificados com base em critérios estabelecidos; 
Os itens de configuração sujeitos a um controle formal são colocados sob baseline; 
A situação dos itens de configuração e das baselines é registrada ao longo do tempo e disponibilizada; Modificações em itens de configuração são controladas; 
O armazenamento, o manuseio e a liberação de itens de configuração e baselines são controlados; 
Auditorias de configuração são realizadas objetivamente para assegurar que as baselines e os itens de configuração estejam íntegros, completos e consistentes; 
As informações de itens de configuração são comunicadas às partes interessadas;

2. Estabeleça a sua própria definição, ou seja, com as suas próprias palavras, o que o MPS.BR considera que seja o propósito da Gerência de Configuração.

É um processo responsável por assegurar que tudo o que foi produzido durante o desenvolvimento do projeto e que ainda se mantenha relevante em alguma etapa de seu ciclo de vida esteja sempre disponível para que quem quer que seja possa acessar.

**Comment by willianjferreira** [comment]
COM APROVEITAMENTO :+1:

**Comment by willianjferreira** [comment]
Pedro, não se esqueça de reabrir os tópicos 01, 02 e 03 pois ficaram SEM APROVEITAMENTO (por conta da entrega fora do prazo). Conforme o tópico 07, é a oportunidade de reabrir e refazer dentro do novo prazo.
